[package]
name = "transaction_processor"
version = "0.0.1"
authors = ["Zhiyuan Zheng <zhiyuan.zheng@yandex.com>"]
edition = "2018"

[dependencies]
entities = { path = "../../entities" }

chardet = "0.2"
encoding = "0.2"
csv = "1.1"
chrono = "0.4"

