CREATE TABLE ACCOUNT
(
    ID      INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME    TEXT UNIQUE,
    BALANCE INTEGER
);

CREATE TABLE CATEGORY
(
    ID   INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT UNIQUE
);

CREATE TABLE "TRANSACTION"
(
    ID       INTEGER PRIMARY KEY AUTOINCREMENT,
    ACCOUNT  INTEGER,
    CATEGORY INTEGER,
    AMOUNT   INTEGER,
    COMMENT  TEXT,
    DATETIME DATETIME
);

CREATE TABLE SECRET
(
    TOKEN TEXT
);

CREATE TABLE DB_VERSION
(
    VERSION   TEXT,
    DEPLOY_AT DATETIME
);

INSERT INTO SECRET (TOKEN) VALUES ('123456');
INSERT INTO DB_VERSION (VERSION, DEPLOY_AT) VALUES ('1_0_0', STRFTIME('%s','now'));
